### ISSUE TITLE
error mdt police in phone

### ISSUE THREAD

**Issue by secret-agent313** [qbcore-framework/qb-phone#90]
Hello, Inside the script of the Bug phone to sent the alarm police . error :
![image](https://user-images.githubusercontent.com/44697398/131487746-1c96a024-f700-48d8-86a3-18dd0b822fea.png)

**Comment by sajad314** [comment]
How can I solve this problem?

**Comment by Eralpozcan** [comment]
This issue occurs when no alarm is sent. Normally you don't experience this. In other words, if you click on the button in case of no alarm, you will have this problem because it will send a coordinate that does not exist.

I posted the solution to this problem. It will be solved after checking/review.
